import { useMutation, useQueries, useQueryClient } from '@tanstack/react-query';
import { useEffect, useMemo, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import {
  Card,
  CardBody,
  CardTitle,
  Col,
  Container,
  Form,
  FormGroup,
  Input,
  Label,
  Modal,
  ModalBody,
  ModalFooter,
  ModalHeader,
  Nav,
  NavItem,
  NavLink,
  Row,
  TabContent,
  TabPane,
  Table,
} from 'reactstrap';
import {
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Line,
  LineChart,
  ReferenceLine,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts';
import { categoriesApi } from '../api/categories';
import { creditCardDebtsApi } from '../api/credit-card-debts';
import { queryKeys } from '../api/query-keys';
import { RenderCreatableSubtypeSelect } from '../UI/functions/render-creatable-subtype-select';
import { RenderPageHeader } from '../UI/functions/render-page-header';
import {
  RenderDangerButton,
  RenderDefaultButton,
  RenderPrimaryButton,
} from '../UI/functions/render-skeleton-button-functions';
import { TagPill } from '../UI/functions/render-tag-pill';
import { Direction } from '../types/enums';
import type {
  CreateCreditCardTransactionRequest,
  CreditCardBalanceAnchor,
  CreditCardComponentType,
  CreditCardTransaction,
  ReconcileCreditCardDebtRequest,
} from '../types/api';

// User-pickable transaction types (Adjustment is system-generated by reconciliation).
const COMPONENTS: CreditCardComponentType[] = ['Charge', 'Payment', 'Interest', 'Fee', 'Refund'];

type CCDisplayComponent = CreditCardComponentType | 'Adjustment';
const DISPLAY_COMPONENTS: CCDisplayComponent[] = [...COMPONENTS, 'Adjustment'];

const COMPONENT_COLORS: Record<CCDisplayComponent, string> = {
  Charge: '#ef4444', // red — debt up
  Payment: '#22c55e', // green — debt down (good)
  Interest: '#f97316', // orange — debt up via accrual
  Fee: '#dc2626', // dark red — debt up via penalty
  Refund: '#10b981', // emerald — debt down via vendor refund
  Adjustment: '#a78bfa', // purple — reconciliation drift (sign depends on direction)
};

// Sign convention is INVERTED from savings — these are debt:
// Charge / Interest / Fee push the balance UP (positive change)
// Payment / Refund pull the balance DOWN (negative change)
const POSITIVE_TO_BALANCE: CreditCardComponentType[] = ['Charge', 'Interest', 'Fee'];

const todayIso = () => new Date().toISOString().slice(0, 10);
const fmt = (n: number) => n.toLocaleString(undefined, { style: 'currency', currency: 'USD' });

function bucketComponent(raw: string | null): CCDisplayComponent | 'Other' {
  if (!raw) return 'Other';
  const normalized = raw.trim().toLowerCase();
  for (const c of DISPLAY_COMPONENTS) {
    if (c.toLowerCase() === normalized) return c;
  }
  return 'Other';
}

function increasesBalance(c: CCDisplayComponent | 'Other'): boolean {
  return c !== 'Other' && c !== 'Adjustment' && POSITIVE_TO_BALANCE.includes(c);
}

// Signed effect on the (debt) balance. Adjustment can go either way, so its sign
// follows the line item's direction (Expense = debt up, Income = debt down).
function signedAmount(t: CreditCardTransaction): number {
  const bucket = bucketComponent(t.componentType);
  if (bucket === 'Other') return 0;
  if (bucket === 'Adjustment') return t.direction === Direction.Expense ? t.amount : -t.amount;
  return increasesBalance(bucket) ? t.amount : -t.amount;
}

function generateMonthRange(startMonth: string, endMonth: string): string[] {
  const result: string[] = [];
  const [sy, sm] = startMonth.split('-').map(Number) as [number, number];
  const [ey, em] = endMonth.split('-').map(Number) as [number, number];
  let year = sy;
  let month = sm;
  while (year < ey || (year === ey && month <= em)) {
    result.push(`${year}-${String(month).padStart(2, '0')}`);
    month++;
    if (month > 12) {
      month = 1;
      year++;
    }
  }
  return result;
}

function addMonths(iso: string, months: number): string {
  const d = new Date(iso);
  d.setMonth(d.getMonth() + months);
  return d.toISOString().slice(0, 10);
}

interface YearTotals {
  year: string;
  Charge: number;
  Payment: number;
  Interest: number;
  Fee: number;
  Refund: number;
  Net: number; // signed: positive = debt grew, negative = debt paid down
  Total: number;
}

export default function CreditCardDetailPage() {
  const { uid } = useParams<{ uid: string }>();
  const queryClient = useQueryClient();

  type TabKey = 'overview' | 'line-items';
  const [activeTab, setActiveTab] = useState<TabKey>('overview');

  // Modal state
  const [modalOpen, setModalOpen] = useState(false);
  const [editingLineItemUid, setEditingLineItemUid] = useState<string | null>(null);
  const [date, setDate] = useState<string>(todayIso());
  const [billingMonth, setBillingMonth] = useState<string>('');
  const [componentType, setComponentType] = useState<CreditCardComponentType>('Charge');
  const [amount, setAmount] = useState<string>('');
  const [tag, setTag] = useState<string | null>(null);
  const [description, setDescription] = useState<string>('');
  const [categoryUid, setCategoryUid] = useState<string>('');
  const [submitError, setSubmitError] = useState<string | null>(null);

  // Reconcile modal state
  const [reconcileOpen, setReconcileOpen] = useState(false);
  const [recDate, setRecDate] = useState<string>(todayIso());
  const [recBalance, setRecBalance] = useState<string>('');
  const [recCategoryUid, setRecCategoryUid] = useState<string>('');
  const [recNote, setRecNote] = useState<string>('');
  const [reconcileError, setReconcileError] = useState<string | null>(null);

  const isEditing = editingLineItemUid !== null;

  const queries = useQueries({
    queries: [
      {
        queryKey: queryKeys.creditCardDebts.detail(uid ?? ''),
        queryFn: () => creditCardDebtsApi.get(uid!),
        enabled: !!uid,
      },
      {
        queryKey: queryKeys.creditCardDebts.transactions(uid ?? ''),
        queryFn: () => creditCardDebtsApi.listTransactions(uid!),
        enabled: !!uid,
      },
      {
        queryKey: queryKeys.categories.list(false),
        queryFn: () => categoriesApi.list(false),
      },
      {
        queryKey: queryKeys.creditCardDebts.anchors(uid ?? ''),
        queryFn: () => creditCardDebtsApi.listAnchors(uid!),
        enabled: !!uid,
      },
    ],
  });

  const [cardQuery, txQuery, categoriesQuery, anchorsQuery] = queries;
  const card = cardQuery.data;
  const transactions: CreditCardTransaction[] = txQuery.data ?? [];
  const categories = categoriesQuery.data ?? [];
  const anchors: CreditCardBalanceAnchor[] = anchorsQuery.data ?? [];

  // No filter — same rationale as savings: a "Credit Card" line item in the ledger
  // can be Income (paid off) or Expense (charged); the user picks whatever fits.
  const eligibleCategories = useMemo(
    () => categories.filter((c) => !c.isArchived),
    [categories],
  );

  useEffect(() => {
    if (eligibleCategories.length === 0) {
      setCategoryUid('');
      return;
    }
    if (!eligibleCategories.some((c) => c.uid === categoryUid)) {
      setCategoryUid(eligibleCategories[0]!.uid);
    }
  }, [eligibleCategories, categoryUid]);

  const tagOptions = useMemo(
    () => Array.from(new Set(transactions.map((t) => t.tag).filter((s): s is string => !!s))),
    [transactions],
  );

  // ---- Aggregations -----------------------------------------------------

  const totals = useMemo(() => {
    const acc: Record<CCDisplayComponent | 'Other' | 'Total' | 'Net', number> = {
      Charge: 0,
      Payment: 0,
      Interest: 0,
      Fee: 0,
      Refund: 0,
      Adjustment: 0,
      Other: 0,
      Total: 0,
      Net: 0,
    };
    for (const t of transactions) {
      const bucket = bucketComponent(t.componentType);
      acc[bucket] += t.amount;
      acc.Total += t.amount;
      acc.Net += signedAmount(t);
    }
    return acc;
  }, [transactions]);

  const utilizationPct = useMemo(() => {
    if (!card || card.creditLimit <= 0) return 0;
    return card.currentBalance / card.creditLimit;
  }, [card]);

  // Net change per month — debt up positive, debt down negative.
  const monthlyChartData = useMemo(() => {
    const byMonth = new Map<string, number>();
    for (const t of transactions) {
      const month = (t.billingMonth ?? t.date).slice(0, 7);
      const signed = signedAmount(t);
      if (signed === 0) continue;
      byMonth.set(month, (byMonth.get(month) ?? 0) + signed);
    }
    if (byMonth.size === 0) return [];
    const sortedMonths = [...byMonth.keys()].sort();
    const allMonths = generateMonthRange(sortedMonths[0]!, sortedMonths[sortedMonths.length - 1]!);
    return allMonths.map((month) => ({ month, net: byMonth.get(month) ?? 0 }));
  }, [transactions]);

  // Per-transaction balance trajectory with same-day merge + time-proportional
  // x-axis. Debt convention: Charge/Interest/Fee increase balance, Payment/Refund
  // decrease it. Walking newest→oldest, balance BEFORE = balance AFTER - signedDelta.
  const balanceTrajectory = useMemo(() => {
    if (!card) return [];
    const validTx = transactions.filter((t) => t.date <= card.currentAsOfDate);
    const sortedDesc = [...validTx].sort((a, b) => b.date.localeCompare(a.date));

    const points: { date: string; timestamp: number; balance: number }[] = [];
    const seenDates = new Set<string>();
    let runningBalance = card.currentBalance;
    points.push({
      date: card.currentAsOfDate,
      timestamp: Date.parse(card.currentAsOfDate),
      balance: runningBalance,
    });
    seenDates.add(card.currentAsOfDate);

    for (const t of sortedDesc) {
      if (!seenDates.has(t.date)) {
        points.push({ date: t.date, timestamp: Date.parse(t.date), balance: runningBalance });
        seenDates.add(t.date);
      }
      const signedDelta = signedAmount(t);
      runningBalance -= signedDelta;
    }

    return points.reverse();
  }, [card, transactions]);

  const yearOverYear = useMemo<YearTotals[]>(() => {
    const byYear = new Map<string, YearTotals>();
    for (const t of transactions) {
      const year = (t.billingMonth ?? t.date).slice(0, 4);
      let row = byYear.get(year);
      if (!row) {
        row = {
          year,
          Charge: 0,
          Payment: 0,
          Interest: 0,
          Fee: 0,
          Refund: 0,
          Net: 0,
          Total: 0,
        };
        byYear.set(year, row);
      }
      const bucket = bucketComponent(t.componentType);
      if (bucket !== 'Other' && bucket !== 'Adjustment') {
        row[bucket] += t.amount;
        row.Total += t.amount;
      }
      row.Net += signedAmount(t);
    }
    return [...byYear.values()].sort((a, b) => b.year.localeCompare(a.year));
  }, [transactions]);

  // ---- Mutations --------------------------------------------------------

  const invalidate = () => {
    void queryClient.invalidateQueries({ queryKey: queryKeys.creditCardDebts.transactions(uid!) });
    void queryClient.invalidateQueries({ queryKey: queryKeys.creditCardDebts.detail(uid!) });
    void queryClient.invalidateQueries({ queryKey: queryKeys.creditCardDebts.anchors(uid!) });
  };

  const createMutation = useMutation({
    mutationFn: (request: CreateCreditCardTransactionRequest) =>
      creditCardDebtsApi.createTransaction(uid!, request),
    onSuccess: () => {
      invalidate();
      setAmount('');
      setDescription('');
      setSubmitError(null);
      setDate((current) => addMonths(current, 1));
      setBillingMonth((current) => (current ? addMonths(`${current}-01`, 1).slice(0, 7) : ''));
    },
    onError: (e) => setSubmitError(e instanceof Error ? e.message : 'Save failed'),
  });

  const updateMutation = useMutation({
    mutationFn: ({ lineItemUid, request }: { lineItemUid: string; request: CreateCreditCardTransactionRequest }) =>
      creditCardDebtsApi.updateTransaction(uid!, lineItemUid, request),
    onSuccess: () => {
      invalidate();
      closeModal();
    },
    onError: (e) => setSubmitError(e instanceof Error ? e.message : 'Save failed'),
  });

  const deleteMutation = useMutation({
    mutationFn: (lineItemUid: string) => creditCardDebtsApi.deleteTransaction(uid!, lineItemUid),
    onSuccess: invalidate,
  });

  const reconcileMutation = useMutation({
    mutationFn: (request: ReconcileCreditCardDebtRequest) =>
      creditCardDebtsApi.reconcile(uid!, request),
    onSuccess: () => {
      invalidate();
      setReconcileOpen(false);
      setReconcileError(null);
    },
    onError: (e) => setReconcileError(e instanceof Error ? e.message : 'Reconcile failed'),
  });

  const deleteAnchorMutation = useMutation({
    mutationFn: (anchorUid: string) => creditCardDebtsApi.deleteAnchor(uid!, anchorUid),
    onSuccess: invalidate,
  });

  const openCreate = () => {
    setEditingLineItemUid(null);
    setDate(todayIso());
    setBillingMonth('');
    setComponentType('Charge');
    setAmount('');
    setTag(null);
    setDescription('');
    setSubmitError(null);
    setModalOpen(true);
  };

  const openEdit = (t: CreditCardTransaction) => {
    setEditingLineItemUid(t.lineItemUID);
    setDate(t.date);
    setBillingMonth(t.billingMonth ? t.billingMonth.slice(0, 7) : '');
    const ct = bucketComponent(t.componentType);
    setComponentType(COMPONENTS.includes(ct as CreditCardComponentType) ? (ct as CreditCardComponentType) : 'Charge');
    setAmount(t.amount.toString());
    setTag(t.tag);
    setDescription(t.description ?? '');
    setCategoryUid(t.categoryUID);
    setSubmitError(null);
    setModalOpen(true);
  };

  const closeModal = () => {
    setModalOpen(false);
    setEditingLineItemUid(null);
    setSubmitError(null);
  };

  const handleSubmit = () => {
    if (!uid) return;
    if (!categoryUid) {
      setSubmitError('Pick a category before saving.');
      return;
    }
    const numAmount = Number(amount);
    if (!Number.isFinite(numAmount) || numAmount <= 0) {
      setSubmitError('Enter an amount greater than zero.');
      return;
    }
    const request: CreateCreditCardTransactionRequest = {
      date,
      billingMonth: billingMonth ? `${billingMonth}-01` : null,
      categoryUID: categoryUid,
      description: description || null,
      componentType,
      amount: numAmount,
      tag: tag && tag.trim() !== '' ? tag : null,
    };
    if (isEditing && editingLineItemUid) {
      updateMutation.mutate({ lineItemUid: editingLineItemUid, request });
    } else {
      createMutation.mutate(request);
    }
  };

  const handleDelete = (t: CreditCardTransaction) => {
    if (window.confirm(`Delete this ${t.componentType ?? 'transaction'} of ${fmt(t.amount)}?`)) {
      deleteMutation.mutate(t.lineItemUID);
    }
  };

  const openReconcile = () => {
    setRecDate(card?.currentAsOfDate ?? todayIso());
    setRecBalance(card ? card.currentBalance.toString() : '');
    setRecCategoryUid(eligibleCategories[0]?.uid ?? '');
    setRecNote('');
    setReconcileError(null);
    setReconcileOpen(true);
  };

  const handleReconcileSubmit = () => {
    if (!uid) return;
    if (!recCategoryUid) {
      setReconcileError('Pick a category for the adjustment.');
      return;
    }
    const asserted = Number(recBalance);
    if (!Number.isFinite(asserted) || asserted < 0) {
      setReconcileError('Enter a balance of zero or more.');
      return;
    }
    reconcileMutation.mutate({
      date: recDate,
      assertedBalance: asserted,
      categoryUID: recCategoryUid,
      note: recNote.trim() || null,
    });
  };

  const handleDeleteAnchor = (anchor: CreditCardBalanceAnchor) => {
    if (window.confirm(`Delete the reconciliation from ${anchor.date} (asserted ${fmt(anchor.assertedBalance)})?`)) {
      deleteAnchorMutation.mutate(anchor.uid);
    }
  };

  // ---- Renders ----------------------------------------------------------

  const renderHeader = () => {
    const subtitle = card
      ? `${card.institution ?? 'Credit Card'} · ${(card.apr * 100).toFixed(2)}% APR · ${fmt(card.creditLimit)} limit`
      : 'Loading...';
    return (
      <RenderPageHeader
        title={card?.name ?? 'Credit Card'}
        subtitle={subtitle}
        rightContent={
          <>
            <Link to="/liabilities" className="text-decoration-none">
              <RenderDefaultButton label="Back" icon="bi-arrow-left" />
            </Link>
            <RenderDefaultButton label="Reconcile" icon="bi-clipboard-check" onClick={openReconcile} />
            <RenderPrimaryButton label="Add transaction" icon="bi-plus-lg" onClick={openCreate} />
          </>
        }
      />
    );
  };

  const renderCardSummary = () => {
    if (!card) return null;
    const stat = (label: string, value: React.ReactNode, color?: string, subtitle?: string) => (
      <div className="d-flex flex-column">
        <span className="stat-card-label lh-1">{label}</span>
        <span className="fw-semibold" style={color ? { color } : undefined}>
          {value}
        </span>
        {subtitle && <span className="stat-card-subtitle">{subtitle}</span>}
      </div>
    );

    // For credit cards, net positive (debt grew) is bad; net negative (debt paid) is good.
    const netColor = totals.Net >= 0 ? COMPONENT_COLORS.Charge : COMPONENT_COLORS.Payment;

    return (
      <Card className="mb-3">
        <CardBody className="py-3">
          <div className="summary-stats-grid">
            {/* Row 1 — column 1 anchor: Current balance */}
            {stat('Current balance', fmt(card.currentBalance))}
            {stat('Credit limit', fmt(card.creditLimit))}
            {stat('APR', `${(card.apr * 100).toFixed(2)}%`)}
            {stat('Min payment', fmt(card.minimumPayment))}
            {stat('Institution', card.institution ?? '—')}
            {/* Row 2 — column 1 anchor: Net change */}
            {stat(
              'Net change (lifetime)',
              `${totals.Net >= 0 ? '+' : '−'}${fmt(Math.abs(totals.Net)).replace(/^[-]/, '')}`,
              netColor,
              totals.Net >= 0 ? 'debt grew' : 'debt paid down',
            )}
            {stat('Total Charges', fmt(totals.Charge), COMPONENT_COLORS.Charge)}
            {stat('Total Payments', fmt(totals.Payment), COMPONENT_COLORS.Payment)}
            {stat('Total Interest + Fees', fmt(totals.Interest + totals.Fee), COMPONENT_COLORS.Interest)}
            {stat(
              'Utilization',
              `${(utilizationPct * 100).toFixed(1)}%`,
              utilizationPct >= 0.3 ? COMPONENT_COLORS.Charge : COMPONENT_COLORS.Payment,
              `${fmt(card.currentBalance)} / ${fmt(card.creditLimit)}`,
            )}
          </div>
        </CardBody>
      </Card>
    );
  };

  const renderTabs = () => (
    <Nav tabs className="mb-3">
      <NavItem>
        <NavLink
          active={activeTab === 'overview'}
          onClick={() => setActiveTab('overview')}
          style={{ cursor: 'pointer' }}
        >
          Overview
        </NavLink>
      </NavItem>
      <NavItem>
        <NavLink
          active={activeTab === 'line-items'}
          onClick={() => setActiveTab('line-items')}
          style={{ cursor: 'pointer' }}
        >
          Line Items
        </NavLink>
      </NavItem>
    </Nav>
  );

  const renderYearlyCards = () => {
    if (yearOverYear.length === 0) {
      return (
        <Card className="mb-3">
          <CardBody className="py-2">
            <span className="stat-card-label">Yearly totals</span>
            <p className="text-muted small mb-0 mt-2">
              Per-year breakdown appears here once transactions are recorded.
            </p>
          </CardBody>
        </Card>
      );
    }
    return (
      <div className="year-cards-scroll">
        <Row className="g-3">
          {yearOverYear.map((row) => {
            const netColor = row.Net >= 0 ? COMPONENT_COLORS.Charge : COMPONENT_COLORS.Payment;
            return (
              <Col xs={12} key={row.year}>
                <Card>
                  <CardBody className="py-2">
                    <div className="d-flex justify-content-between align-items-baseline mb-2">
                      <span className="stat-card-label">{row.year}</span>
                      <strong style={{ fontSize: '1.05rem', color: netColor }}>
                        {row.Net >= 0 ? '+' : '−'}
                        {fmt(Math.abs(row.Net)).replace(/^[-]/, '')}
                      </strong>
                    </div>
                    <div className="year-card-breakdown">
                      <span className="year-cell-label">Charges</span>
                      <span className="year-cell-label">Payments</span>
                      <span className="year-cell-label">Interest + Fees</span>
                      <span className="year-cell-value" style={{ color: COMPONENT_COLORS.Charge }}>
                        {fmt(row.Charge)}
                      </span>
                      <span className="year-cell-value" style={{ color: COMPONENT_COLORS.Payment }}>
                        {fmt(row.Payment)}
                      </span>
                      <span className="year-cell-value" style={{ color: COMPONENT_COLORS.Interest }}>
                        {fmt(row.Interest + row.Fee)}
                      </span>
                      <span className="year-cell-extra" />
                      <span className="year-cell-extra">
                        {row.Refund > 0 ? `+${fmt(row.Refund)} refunds` : ''}
                      </span>
                      <span className="year-cell-extra" />
                    </div>
                  </CardBody>
                </Card>
              </Col>
            );
          })}
        </Row>
      </div>
    );
  };

  const renderBalanceChart = () => {
    if (!card) return null;
    if (balanceTrajectory.length <= 1) {
      return (
        <Card className="mb-3">
          <CardBody className="py-2">
            <CardTitle tag="h6" className="mb-1">Balance over time</CardTitle>
            <p className="text-muted mb-0">Add transactions to populate the balance line.</p>
          </CardBody>
        </Card>
      );
    }
    return (
      <Card className="mb-3">
        <CardBody className="py-2">
          <div className="d-flex justify-content-between align-items-baseline mb-1">
            <CardTitle tag="h6" className="mb-0">Balance over time</CardTitle>
            <small className="text-muted">
              from {fmt(card.currentBalance)} · {balanceTrajectory.length - 1} transaction
              {balanceTrajectory.length - 1 === 1 ? '' : 's'}
            </small>
          </div>
          <div style={{ width: '100%', height: 200 }}>
            <ResponsiveContainer>
              <LineChart data={balanceTrajectory} margin={{ top: 5, right: 15, left: 0, bottom: 0 }}>
                <CartesianGrid stroke="rgba(255,255,255,0.08)" />
                <XAxis
                  dataKey="timestamp"
                  type="number"
                  scale="time"
                  domain={['dataMin', 'dataMax']}
                  stroke="rgba(255,255,255,0.55)"
                  tick={{ fontSize: 11 }}
                  tickFormatter={(ts: number) => new Date(ts).toISOString().slice(0, 10)}
                />
                <YAxis
                  stroke="rgba(255,255,255,0.55)"
                  tickFormatter={(v) => `$${(v / 1000).toFixed(0)}k`}
                  tick={{ fontSize: 11 }}
                />
                <Tooltip
                  contentStyle={{ backgroundColor: '#20242c', border: '1px solid #6b21a8' }}
                  formatter={(value: number) => fmt(value)}
                  labelFormatter={(ts: number) => new Date(ts).toISOString().slice(0, 10)}
                />
                <Line
                  type="monotone"
                  dataKey="balance"
                  stroke="var(--enlil-accent-bright)"
                  strokeWidth={2}
                  dot={{ r: 2.5, fill: 'var(--enlil-accent-bright)' }}
                  activeDot={{ r: 4 }}
                  connectNulls={false}
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        </CardBody>
      </Card>
    );
  };

  const renderMonthlyChart = () => {
    if (monthlyChartData.length === 0) {
      return (
        <Card className="mb-3">
          <CardBody className="py-2">
            <CardTitle tag="h6" className="mb-1">Monthly net change</CardTitle>
            <p className="text-muted mb-0">No transactions yet.</p>
          </CardBody>
        </Card>
      );
    }
    return (
      <Card className="mb-3">
        <CardBody className="py-2">
          <CardTitle tag="h6" className="mb-1">Monthly net change</CardTitle>
          <div style={{ width: '100%', height: 200 }}>
            <ResponsiveContainer>
              <BarChart data={monthlyChartData} margin={{ top: 5, right: 15, left: 0, bottom: 0 }}>
                <CartesianGrid stroke="rgba(255,255,255,0.08)" vertical={false} />
                <XAxis dataKey="month" stroke="rgba(255,255,255,0.55)" tick={{ fontSize: 11 }} />
                <YAxis
                  stroke="rgba(255,255,255,0.55)"
                  tickFormatter={(v) => `$${(v / 1000).toFixed(0)}k`}
                  tick={{ fontSize: 11 }}
                />
                <ReferenceLine y={0} stroke="rgba(255,255,255,0.35)" />
                <Tooltip
                  cursor={{ fill: 'rgba(139, 92, 246, 0.1)' }}
                  contentStyle={{ backgroundColor: '#20242c', border: '1px solid #6b21a8' }}
                  formatter={(value: number) => `${value >= 0 ? '+' : '−'}${fmt(Math.abs(value))}`}
                />
                <Bar dataKey="net">
                  {monthlyChartData.map((entry, idx) => (
                    <Cell
                      key={idx}
                      fill={entry.net >= 0 ? COMPONENT_COLORS.Charge : COMPONENT_COLORS.Payment}
                    />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        </CardBody>
      </Card>
    );
  };

  const renderHistory = () => (
    <Card className="mb-0">
      <CardBody>
        <CardTitle tag="h5">Transaction history (newest first)</CardTitle>
        {transactions.length === 0 ? (
          <p className="text-muted mb-0">No transactions recorded yet.</p>
        ) : (
          <Table hover responsive size="sm" className="mb-0">
            <thead>
              <tr>
                <th>Date</th>
                <th>Billing month</th>
                <th>Type</th>
                <th>Tag</th>
                <th>Description</th>
                <th>Category</th>
                <th className="text-end">Amount</th>
                <th />
              </tr>
            </thead>
            <tbody>
              {transactions.map((t) => {
                const ct = bucketComponent(t.componentType);
                const debtUp = signedAmount(t) >= 0;
                const color = ct === 'Other' ? undefined : COMPONENT_COLORS[ct];
                const isAdjustment = ct === 'Adjustment';
                return (
                  <tr key={t.lineItemUID}>
                    <td>{t.date}</td>
                    <td>{t.billingMonth ? t.billingMonth.slice(0, 7) : '—'}</td>
                    <td style={{ color }} className="fw-semibold">
                      {t.componentType ?? '—'}
                    </td>
                    <td>{t.tag ? <TagPill tag={t.tag} /> : <span className="text-muted">—</span>}</td>
                    <td>{t.description ?? '—'}</td>
                    <td>{t.categoryName}</td>
                    <td className="text-end fw-semibold" style={{ color }}>
                      {debtUp ? '+' : '−'}
                      {fmt(t.amount).replace(/^[-]/, '')}
                    </td>
                    <td>
                      <div className="d-flex gap-2 justify-content-end">
                        {!isAdjustment && (
                          <RenderDefaultButton
                            label="Edit"
                            icon="bi-pencil-square"
                            onClick={() => openEdit(t)}
                          />
                        )}
                        <RenderDangerButton
                          label="Delete"
                          icon="bi-trash"
                          onClick={() => handleDelete(t)}
                        />
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </Table>
        )}
      </CardBody>
    </Card>
  );

  const renderReconciliations = () => (
    <Card className="mt-3 mb-0">
      <CardBody>
        <div className="d-flex justify-content-between align-items-center mb-2">
          <CardTitle tag="h5" className="mb-0">Reconciliations</CardTitle>
          <RenderDefaultButton
            label="Reconcile balance"
            icon="bi-clipboard-check"
            onClick={openReconcile}
          />
        </div>
        <p className="text-muted small">
          A reconciliation asserts the card&apos;s true balance on a date. The running balance is
          computed from the latest reconciliation plus the line items after it; any drift is recorded
          as an Adjustment line item.
        </p>
        {anchors.length === 0 ? (
          <p className="text-muted mb-0">No reconciliations yet.</p>
        ) : (
          <Table hover responsive size="sm" className="mb-0">
            <thead>
              <tr>
                <th>Date</th>
                <th>Type</th>
                <th className="text-end">Asserted balance</th>
                <th className="text-end">Adjustment</th>
                <th>Note</th>
                <th />
              </tr>
            </thead>
            <tbody>
              {anchors.map((a) => {
                const adjColor =
                  a.adjustmentAmount === 0
                    ? undefined
                    : a.adjustmentAmount > 0
                      ? COMPONENT_COLORS.Charge
                      : COMPONENT_COLORS.Payment;
                return (
                  <tr key={a.uid}>
                    <td>{a.date}</td>
                    <td>{a.isOpening ? 'Opening' : 'Reconcile'}</td>
                    <td className="text-end fw-semibold">{fmt(a.assertedBalance)}</td>
                    <td className="text-end" style={{ color: adjColor }}>
                      {a.adjustmentAmount === 0
                        ? '—'
                        : `${a.adjustmentAmount > 0 ? '+' : '−'}${fmt(Math.abs(a.adjustmentAmount))}`}
                    </td>
                    <td>{a.note ?? '—'}</td>
                    <td className="text-end">
                      {!a.isOpening && (
                        <RenderDangerButton
                          label="Delete"
                          icon="bi-trash"
                          onClick={() => handleDeleteAnchor(a)}
                        />
                      )}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </Table>
        )}
      </CardBody>
    </Card>
  );

  const renderReconcileModal = () => (
    <Modal isOpen={reconcileOpen} toggle={() => setReconcileOpen(false)}>
      <ModalHeader toggle={() => setReconcileOpen(false)}>Reconcile balance</ModalHeader>
      <ModalBody>
        <Form>
          <FormGroup>
            <Label for="cc-rec-date">Statement / as-of date</Label>
            <Input
              id="cc-rec-date"
              type="date"
              value={recDate}
              onChange={(e) => setRecDate(e.target.value)}
            />
          </FormGroup>
          <FormGroup>
            <Label for="cc-rec-balance">Asserted balance</Label>
            <Input
              id="cc-rec-balance"
              type="number"
              step="0.01"
              placeholder="0.00"
              value={recBalance}
              onChange={(e) => setRecBalance(e.target.value)}
            />
          </FormGroup>
          <FormGroup>
            <Label for="cc-rec-category">Adjustment category</Label>
            <Input
              id="cc-rec-category"
              type="select"
              value={recCategoryUid}
              onChange={(e) => setRecCategoryUid(e.target.value)}
            >
              {eligibleCategories.length === 0 && <option value="">No categories</option>}
              {eligibleCategories.map((c) => (
                <option key={c.uid} value={c.uid}>
                  {c.name}
                </option>
              ))}
            </Input>
          </FormGroup>
          <FormGroup>
            <Label for="cc-rec-note">Note (optional)</Label>
            <Input
              id="cc-rec-note"
              type="text"
              value={recNote}
              onChange={(e) => setRecNote(e.target.value)}
              placeholder="e.g., March statement"
            />
          </FormGroup>
          {reconcileError && <p className="text-danger mb-0">{reconcileError}</p>}
          <p className="text-muted small mb-0">
            If this differs from the computed balance, the difference is recorded as an Adjustment
            line item in the chosen category.
          </p>
        </Form>
      </ModalBody>
      <ModalFooter>
        <RenderDefaultButton
          label="Cancel"
          onClick={() => setReconcileOpen(false)}
          disabled={reconcileMutation.isPending}
        />
        <RenderPrimaryButton
          label={reconcileMutation.isPending ? 'Saving...' : 'Reconcile'}
          icon="bi-check-lg"
          onClick={handleReconcileSubmit}
          disabled={reconcileMutation.isPending}
        />
      </ModalFooter>
    </Modal>
  );

  const renderTransactionModal = () => {
    const isPending = createMutation.isPending || updateMutation.isPending;
    return (
      <Modal isOpen={modalOpen} toggle={closeModal} size="lg">
        <ModalHeader toggle={closeModal}>
          {isEditing ? 'Edit transaction' : 'Add transaction'}
        </ModalHeader>
        <ModalBody>
          <Form>
            <Row className="g-2">
              <FormGroup className="col-md-3">
                <Label for="cc-tx-type">Type</Label>
                <Input
                  id="cc-tx-type"
                  type="select"
                  value={componentType}
                  onChange={(e) => setComponentType(e.target.value as CreditCardComponentType)}
                >
                  {COMPONENTS.map((c) => (
                    <option key={c} value={c}>
                      {c}
                    </option>
                  ))}
                </Input>
              </FormGroup>
              <FormGroup className="col-md-3">
                <Label for="cc-tx-date">Date</Label>
                <Input
                  id="cc-tx-date"
                  type="date"
                  value={date}
                  onChange={(e) => setDate(e.target.value)}
                />
              </FormGroup>
              <FormGroup className="col-md-3">
                <Label for="cc-tx-billing-month">
                  Billing month <span className="text-muted">(optional)</span>
                </Label>
                <Input
                  id="cc-tx-billing-month"
                  type="month"
                  value={billingMonth}
                  onChange={(e) => setBillingMonth(e.target.value)}
                />
              </FormGroup>
              <FormGroup className="col-md-3">
                <Label for="cc-tx-amount">Amount</Label>
                <Input
                  id="cc-tx-amount"
                  type="number"
                  step="0.01"
                  placeholder="0.00"
                  value={amount}
                  onChange={(e) => setAmount(e.target.value)}
                />
              </FormGroup>
              <FormGroup className="col-md-6">
                <Label for="cc-tx-category">Category</Label>
                <Input
                  id="cc-tx-category"
                  type="select"
                  value={categoryUid}
                  onChange={(e) => setCategoryUid(e.target.value)}
                >
                  {eligibleCategories.length === 0 && <option value="">No categories</option>}
                  {eligibleCategories.map((c) => (
                    <option key={c.uid} value={c.uid}>
                      {c.name}
                    </option>
                  ))}
                </Input>
              </FormGroup>
              <FormGroup className="col-md-6">
                <Label for="cc-tx-tag">
                  Tag <span className="text-muted">(grouping — optional)</span>
                </Label>
                <RenderCreatableSubtypeSelect
                  id="cc-tx-tag"
                  value={tag}
                  options={tagOptions}
                  onChange={setTag}
                  placeholder="e.g., Travel, Groceries, Auto-pay"
                />
              </FormGroup>
              <FormGroup className="col-12">
                <Label for="cc-tx-description">Description (the "why") — optional</Label>
                <Input
                  id="cc-tx-description"
                  type="textarea"
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="e.g., Lunch with team, monthly statement payment"
                />
              </FormGroup>
            </Row>
            {submitError && <p className="text-danger mt-2 mb-0">{submitError}</p>}
            {!isEditing && (
              <p className="text-muted small mt-3 mb-0">
                Tip: after saving, the date advances one month and the form keeps your type, category &amp; tag
                so you can keep adding without reopening.
              </p>
            )}
          </Form>
        </ModalBody>
        <ModalFooter>
          <RenderDefaultButton
            label={isEditing ? 'Cancel' : 'Done'}
            onClick={closeModal}
            disabled={isPending}
          />
          <RenderPrimaryButton
            label={
              isPending
                ? 'Saving...'
                : isEditing
                  ? 'Save changes'
                  : 'Save & add another'
            }
            icon={isEditing ? 'bi-check-lg' : 'bi-plus-lg'}
            onClick={handleSubmit}
            disabled={isPending}
          />
        </ModalFooter>
      </Modal>
    );
  };

  if (cardQuery.isLoading) {
    return (
      <Container fluid className="py-4">
        <p>Loading credit card…</p>
      </Container>
    );
  }
  if (!card) {
    return (
      <Container fluid className="py-4">
        <p className="text-danger">Credit card not found.</p>
        <Link to="/liabilities">Back to liabilities</Link>
      </Container>
    );
  }

  return (
    <Container fluid className="py-4 mortgage-detail-page">
      {renderHeader()}
      {renderCardSummary()}
      {renderTabs()}
      <TabContent activeTab={activeTab}>
        <TabPane tabId="overview" className="overview-pane">
          {activeTab === 'overview' && (
            <Row className="g-3">
              <Col xl={4}>{renderYearlyCards()}</Col>
              <Col xl={8}>
                {renderBalanceChart()}
                {renderMonthlyChart()}
              </Col>
            </Row>
          )}
        </TabPane>
        <TabPane tabId="line-items" className="line-items-pane">
          {activeTab === 'line-items' && (
            <>
              {renderHistory()}
              {renderReconciliations()}
            </>
          )}
        </TabPane>
      </TabContent>
      {renderTransactionModal()}
      {renderReconcileModal()}
    </Container>
  );
}
