// <auto-generated />
using System;
using EnlilFinancialPlanning.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnlilFinancialPlanning.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260508214646_AddSupportToSavingsForLineItemManagement")]
    partial class AddSupportToSavingsForLineItemManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.AmortizationEntry", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Interest")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("MortgageDebtUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PaymentNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Principal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemainingBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UID");

                    b.HasIndex("MortgageDebtUID", "PaymentNumber")
                        .IsUnique();

                    b.ToTable("AmortizationEntries", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.CreditCardDebt", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("APR")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("CurrentAsOfDate")
                        .HasColumnType("date");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Institution")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("MinimumPayment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UID");

                    b.ToTable("CreditCardDebts", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.CreditCardDebtSnapshot", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CreditCardDebtUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.HasKey("UID");

                    b.HasIndex("CreditCardDebtUID", "Date");

                    b.ToTable("CreditCardDebtSnapshots", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.Holding", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<Guid>("LongTermContainerUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Units")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("UID");

                    b.HasIndex("LongTermContainerUID");

                    b.ToTable("Holdings", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.HoldingSnapshot", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("HoldingUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Units")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("UID");

                    b.HasIndex("HoldingUID", "Date");

                    b.ToTable("HoldingSnapshots", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.LineItemAllocation", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("AffectsLinkedBalance")
                        .HasColumnType("bit");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("BillingMonth")
                        .HasColumnType("date");

                    b.Property<string>("ComponentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("LineItemUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LinkedEntityType")
                        .HasColumnType("int");

                    b.Property<Guid>("LinkedEntityUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UID");

                    b.HasIndex("LineItemUID");

                    b.HasIndex("LinkedEntityType", "LinkedEntityUID");

                    b.ToTable("LineItemAllocations", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.LongTermContainer", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateOnly>("CurrentAsOfDate")
                        .HasColumnType("date");

                    b.Property<decimal>("CurrentValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Institution")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UID");

                    b.ToTable("LongTermContainers", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.LongTermItem", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateOnly>("CurrentAsOfDate")
                        .HasColumnType("date");

                    b.Property<decimal>("CurrentValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Subtype")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UID");

                    b.ToTable("LongTermItems", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.LongTermItemSnapshot", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("LongTermItemUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UID");

                    b.HasIndex("LongTermItemUID", "Date");

                    b.ToTable("LongTermItemSnapshots", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.MortgageDebt", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateOnly>("CurrentAsOfDate")
                        .HasColumnType("date");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EscrowMonthly")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Institution")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("InterestRate")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<Guid?>("LinkedRecurringTemplateUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LoanType")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyPaymentPI")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("OriginalPrincipal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PMIMonthly")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("TermMonths")
                        .HasColumnType("int");

                    b.HasKey("UID");

                    b.HasIndex("LinkedRecurringTemplateUID");

                    b.ToTable("MortgageDebts", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.MortgageDebtSnapshot", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("MortgageDebtUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UID");

                    b.HasIndex("MortgageDebtUID", "Date");

                    b.ToTable("MortgageDebtSnapshots", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.RetirementContainer", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<DateOnly>("CurrentAsOfDate")
                        .HasColumnType("date");

                    b.Property<decimal>("CurrentValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Institution")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UID");

                    b.ToTable("RetirementContainers", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.RetirementHolding", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateOnly>("AsOfDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("RetirementContainerUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Units")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("UID");

                    b.HasIndex("RetirementContainerUID");

                    b.ToTable("RetirementHoldings", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.RetirementHoldingSnapshot", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("RetirementHoldingUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Units")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("UID");

                    b.HasIndex("RetirementHoldingUID", "Date");

                    b.ToTable("RetirementHoldingSnapshots", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.Savings", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("CompoundingFrequency")
                        .HasColumnType("int");

                    b.Property<decimal>("CurrentRate")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<DateOnly>("CurrentRateAsOfDate")
                        .HasColumnType("date");

                    b.Property<decimal>("CurrentValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("CurrentValueAsOfDate")
                        .HasColumnType("date");

                    b.Property<string>("Institution")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Subtype")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UID");

                    b.ToTable("Savings", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.SavingsRateSnapshot", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Rate")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<Guid>("SavingsUID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UID");

                    b.HasIndex("SavingsUID", "Date");

                    b.ToTable("SavingsRateSnapshots", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.SavingsValueSnapshot", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("SavingsUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UID");

                    b.HasIndex("SavingsUID", "Date");

                    b.ToTable("SavingsValueSnapshots", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.SimpleAsset", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateOnly>("CurrentAsOfDate")
                        .HasColumnType("date");

                    b.Property<decimal>("CurrentValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Subtype")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UID");

                    b.ToTable("SimpleAssets", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.SimpleAssetSnapshot", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("SimpleAssetUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UID");

                    b.HasIndex("SimpleAssetUID", "Date");

                    b.ToTable("SimpleAssetSnapshots", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.Category", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.LineItem", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CategoryUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<Guid?>("SourceTemplateUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("WasManuallyEdited")
                        .HasColumnType("bit");

                    b.HasKey("UID");

                    b.HasIndex("CategoryUID");

                    b.HasIndex("Date");

                    b.HasIndex("SourceTemplateUID");

                    b.ToTable("LineItems", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.RecurringTemplate", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Cadence")
                        .HasColumnType("int");

                    b.Property<Guid>("CategoryUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("int");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("IntervalDays")
                        .HasColumnType("int");

                    b.Property<int?>("MonthOfQuarter")
                        .HasColumnType("int");

                    b.Property<int?>("MonthOfYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<bool>("UseLastDayOfMonth")
                        .HasColumnType("bit");

                    b.HasKey("UID");

                    b.HasIndex("CategoryUID");

                    b.HasIndex("StartDate");

                    b.ToTable("RecurringTemplates", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.AmortizationEntry", b =>
                {
                    b.HasOne("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.MortgageDebt", "MortgageDebt")
                        .WithMany("AmortizationSchedule")
                        .HasForeignKey("MortgageDebtUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MortgageDebt");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.CreditCardDebtSnapshot", b =>
                {
                    b.HasOne("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.CreditCardDebt", "CreditCardDebt")
                        .WithMany("Snapshots")
                        .HasForeignKey("CreditCardDebtUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreditCardDebt");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.Holding", b =>
                {
                    b.HasOne("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.LongTermContainer", "LongTermContainer")
                        .WithMany("Holdings")
                        .HasForeignKey("LongTermContainerUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LongTermContainer");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.HoldingSnapshot", b =>
                {
                    b.HasOne("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.Holding", "Holding")
                        .WithMany("Snapshots")
                        .HasForeignKey("HoldingUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Holding");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.LineItemAllocation", b =>
                {
                    b.HasOne("EnlilFinancialPlanning.Api.Data.Entities.LineItem", "LineItem")
                        .WithMany()
                        .HasForeignKey("LineItemUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LineItem");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.LongTermItemSnapshot", b =>
                {
                    b.HasOne("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.LongTermItem", "LongTermItem")
                        .WithMany("Snapshots")
                        .HasForeignKey("LongTermItemUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LongTermItem");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.MortgageDebt", b =>
                {
                    b.HasOne("EnlilFinancialPlanning.Api.Data.Entities.RecurringTemplate", "LinkedRecurringTemplate")
                        .WithMany()
                        .HasForeignKey("LinkedRecurringTemplateUID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedRecurringTemplate");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.MortgageDebtSnapshot", b =>
                {
                    b.HasOne("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.MortgageDebt", "MortgageDebt")
                        .WithMany("Snapshots")
                        .HasForeignKey("MortgageDebtUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MortgageDebt");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.RetirementHolding", b =>
                {
                    b.HasOne("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.RetirementContainer", "RetirementContainer")
                        .WithMany("Holdings")
                        .HasForeignKey("RetirementContainerUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RetirementContainer");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.RetirementHoldingSnapshot", b =>
                {
                    b.HasOne("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.RetirementHolding", "RetirementHolding")
                        .WithMany("Snapshots")
                        .HasForeignKey("RetirementHoldingUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RetirementHolding");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.SavingsRateSnapshot", b =>
                {
                    b.HasOne("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.Savings", "Savings")
                        .WithMany("RateSnapshots")
                        .HasForeignKey("SavingsUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Savings");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.SavingsValueSnapshot", b =>
                {
                    b.HasOne("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.Savings", "Savings")
                        .WithMany("ValueSnapshots")
                        .HasForeignKey("SavingsUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Savings");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.SimpleAssetSnapshot", b =>
                {
                    b.HasOne("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.SimpleAsset", "SimpleAsset")
                        .WithMany("Snapshots")
                        .HasForeignKey("SimpleAssetUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimpleAsset");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.LineItem", b =>
                {
                    b.HasOne("EnlilFinancialPlanning.Api.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnlilFinancialPlanning.Api.Data.Entities.RecurringTemplate", "SourceTemplate")
                        .WithMany("SeededLineItems")
                        .HasForeignKey("SourceTemplateUID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("SourceTemplate");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.RecurringTemplate", b =>
                {
                    b.HasOne("EnlilFinancialPlanning.Api.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.CreditCardDebt", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.Holding", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.LongTermContainer", b =>
                {
                    b.Navigation("Holdings");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.LongTermItem", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.MortgageDebt", b =>
                {
                    b.Navigation("AmortizationSchedule");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.RetirementContainer", b =>
                {
                    b.Navigation("Holdings");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.RetirementHolding", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.Savings", b =>
                {
                    b.Navigation("RateSnapshots");

                    b.Navigation("ValueSnapshots");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.AssetsLiabilities.SimpleAsset", b =>
                {
                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.RecurringTemplate", b =>
                {
                    b.Navigation("SeededLineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
