// <auto-generated />
using System;
using EnlilFinancialPlanning.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EnlilFinancialPlanning.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.Category", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.LineItem", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("CategoryUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<Guid?>("SourceTemplateUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("WasManuallyEdited")
                        .HasColumnType("bit");

                    b.HasKey("UID");

                    b.HasIndex("CategoryUID");

                    b.HasIndex("Date");

                    b.HasIndex("SourceTemplateUID");

                    b.ToTable("LineItems", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.RecurringTemplate", b =>
                {
                    b.Property<Guid>("UID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Cadence")
                        .HasColumnType("int");

                    b.Property<Guid>("CategoryUID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("int");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("IntervalDays")
                        .HasColumnType("int");

                    b.Property<int?>("MonthOfQuarter")
                        .HasColumnType("int");

                    b.Property<int?>("MonthOfYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<bool>("UseLastDayOfMonth")
                        .HasColumnType("bit");

                    b.HasKey("UID");

                    b.HasIndex("CategoryUID");

                    b.HasIndex("StartDate");

                    b.ToTable("RecurringTemplates", (string)null);
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.LineItem", b =>
                {
                    b.HasOne("EnlilFinancialPlanning.Api.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EnlilFinancialPlanning.Api.Data.Entities.RecurringTemplate", "SourceTemplate")
                        .WithMany("SeededLineItems")
                        .HasForeignKey("SourceTemplateUID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("SourceTemplate");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.RecurringTemplate", b =>
                {
                    b.HasOne("EnlilFinancialPlanning.Api.Data.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryUID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EnlilFinancialPlanning.Api.Data.Entities.RecurringTemplate", b =>
                {
                    b.Navigation("SeededLineItems");
                });
#pragma warning restore 612, 618
        }
    }
}
